### PR TITLE
Fix links to project files that result in 404s

### LINKED ISSUE #32: Links to project files result in 404
### General Summary

We sometimes link to source files directly (in contrast to linking to documentation files), for example [when mentioning some project configuration files](https://dev.enso.org/docs/enso/CONTRIBUTING.html#system-requirements).

These links do not work currently in the documentation (but they work correctly when viewed on GitHub). It would be great if they would also work in the docs, probably linking to the source code in the `main` branch.

### Steps to Reproduce

1. Go to https://dev.enso.org/docs/enso/CONTRIBUTING.html#system-requirements
2. Click on the `build.sbt` link

### Expected Result

I see the file contents of `build.sbt` file.

### Actual Result

Nothing happens at all, if I open it in a new tab I get a 404 error.

### PR DESCRIPTION
**Pull request by npentrel**
### Pull Request Description

Fix https://github.com/enso-org/enso-org.github.io/issues/32. This pull request replaces the broken relative references with absolute references. 

### Checklist

Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
- [x] All code has been tested where possible.

### CODE REVIEW

**Comment by joenash** [comment]
@npentrel to close the ➿, having a look into whether this is fixable on the jekyll side (i.e. in the handling of relative links) because that would mean docs writers don't have to change how they write the docs. However I think this is probably due to the use of [this gem](https://github.com/benbalter/jekyll-relative-links) and it assuming that all relative links are to other docs in the static site, which is why it's failing to make good links for these build files...looking into it

**Comment by joenash** [comment]
@npentrel Ah, ok think I've got it! 

`jekyll-relative-links` can be set to [exclude](https://github.com/benbalter/jekyll-relative-links#excluding-files) certain directories and files from it's conversion in the site's `_config.yml`. So the files for which you've had to change the URLs to absolute here can be added to that instead, or the directory when that directory isn't root, I think.

**Comment by npentrel** [comment]
It seems you can only exclude whole files or whole directories. There's files that contain relative links to the repo and to the docs - so excluding the file would break the other links. 🤷‍♀️

**Comment by joenash** [comment]
Hmm ok. I'd like to find a solution to this that doesn't involve diving into that gem...I would prefer we do absolute paths in that case but as they're GitHub URLs, @iamrecursion's concern is that will break docs navigation in local clones.

**Comment by iamrecursion** [comment]
Hi @npentrel! Thanks so much for this contribution! Has there been any luck fixing this on the Jekyll side?

**Comment by joenash** [comment]
This is a substantial problem on the Jekyll side. I'm going to close this for now whilst I find a way to do it, but there is a chance this could circle back round to it being easier to absolute link these things.

**Pull request closed without merging**
