### PR TITLE
README changes ahead of IDE tester packages

### PR DESCRIPTION
**Pull request by joenash**
### Pull Request Description

This PR makes a suite of changes to the README ahead of more widespread availability of Enso packages. 

- At request of @wdanilo, repositioning `enso_org/enso` as the entry point for the project as a whole on GitHub.
  - References to installing/using Enso refer to the full application rather than the Engine.
  - Distinct project components section detailing engine and IDE projects.
- Updating descriptions to use elements from our new website copy. 
  - Input on this welcome: I would prefer to use far more grounded and toned down text than that which we want on our landing page.
- Included screenshots and videos of the new IDE in action now that we can do that.
- More user focused getting started bullets.
- Rearranged some sections 

Aside from comments and feedback on the above, the following is still to do:
- Is linking to IDE Releases accurate for the tester packages?
- @wdanilo mentioned being aware of a method to show the appropriate logo for darkmode/light mode. I couldn't find anything useful, any pointers would be great.
- Now that we have GitHub Discussions, do we want to have any CTA for that?

### Checklist

Please include the following checklist in your PR:

- [ ] The documentation has been updated if necessary.
- [ ] All code conforms to the [Scala](https://github.com/enso-org/enso/blob/main/docs/style-guide/scala.md), [Java](https://github.com/enso-org/enso/blob/main/docs/style-guide/java.md), and [Rust](https://github.com/enso-org/enso/blob/main/docs/style-guide/rust.md) style guides.
- [x] All documentation and configuration conforms to the [markdown](https://github.com/enso-org/enso/blob/main/docs/style-guide/markdown.md) and [YAML](https://github.com/enso-org/enso/blob/main/docs/style-guide/yaml.md) style guides.
   - slight md styleguide deviation for the tagline "get insights you can act on, fast" using a h2 but not being title cased. Open to changing that to another element, originally it was a `>`. 
- [ ] All code has been tested where possible.

### CODE REVIEW

**Comment by joenash** [comment]
Oop, styling issue. The right aligned logo causes one of the shields to overflow at current size. It has to be silly tiny to prevent that. 

Given we now call out to joining the discord in the getting started bullets, anyone object to dropping the discord shield? Alternatively one of the license shields...having 2 may be gratuitous?

**Comment by iamrecursion** [comment]
> * Updating descriptions to use elements from our new website copy.

Currently this seems way too marketing-y. Like, it's all well and good to say what we do well, but this just makes me want to stop reading.

> * Included screenshots and videos of the new IDE in action now that we can do that.

Can we please centre these? They look really odd being left-justified. They also look generically awful on the dark mode scheme, but I don't know if there's much we can do about that. Also, the "See it in action" link is butted right up against the screenshot and shouldn't be. Please make sure that there's a line break between it and the screenie.

> * Is linking to IDE Releases accurate for the tester packages?

Yes.

> * @wdanilo mentioned being aware of a method to show the appropriate logo for darkmode/light mode. I couldn't find anything useful, any pointers would be great.

You can embed an SVG of the logo that changes based on `prefers-color-scheme`, I believe. This does, however, require that we _have_ an SVG of the logo. 

> * Now that we have GitHub Discussions, do we want to have any CTA for that?

Yes, please. I've removed all of the discussion and question related labels from issues, so directing people to discussions for those things is a must. 

Some additional questions and comments:

- How does this look on the GH Mobile site and mobile app?
- Please highlight the contributing section in the getting started section. GitHub is a technical community, and while I understand the desire for a more marketing-oriented readme, I despise that it then makes it much more difficult and less obvious to find contributing information for those interested.

**Comment by joenash** [comment]
Thanks for the detailed comments :sparkles: 

> Currently this seems way too marketing-y. Like, it's all well and good to say what we do well, but this just makes me want to stop reading.

Ugh I was afraid of this - will do another pass on it. 

> Can we please centre these? They look really odd being left-justified. 

Sure thing!

> They also look generically awful on the dark mode scheme, but I don't know if there's much we can do about that. 

Yeah I'm not sure...hopefully in the future something like [this](https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981) lands and we can show different screens. 

> Also, the "See it in action" link is butted right up against the screenshot and shouldn't be. Please make sure that there's a line break between it and the screenie.

:+1: 

> You can embed an SVG of the logo that changes based on `prefers-color-scheme`, I believe. 

Yeah I saw this but the GitHub dark mode does currently not follow the system preferences. Supposedly it will after it leaves beta, but who knows when that will be. But right now, it defaults to light mode, and the user has to set it to follow preferences. If we make a light Enso logo hooked on `prefers-color-scheme` and a user with darkmode OS but default GitHub rocks up, they won't be able to see the logo. So I'm not sure it's usable right now, given the power of defaults. There's also the case where a user has Darkmode OS but specifically choosesn light mode GitHub (like me 🙃). GitHub really need to provide a way to hook into the currently used theme/user setting.

> This does, however, require that we _have_ an SVG of the logo. 

Nonetheless, let's prep for it in case Darkmode leaves beta. 

@wdanilo Can you generate some .svg logos please? I believe [all of the logos](https://github.com/enso-org/ide/issues/227) in the issue are png. 

> so directing people to discussions for those things is a must. 

On it

> How does this look on the GH Mobile site and mobile app?

Logo far too hefty - I might just move the shields out of that right adjusted area. 

> Please highlight the contributing section in the getting started section. 

No problem

> GitHub is a technical community, and while I understand the desire for a more marketing-oriented readme, I despise that it then makes it much more difficult and less obvious to find contributing information for those interested.

Having said that, I think this reaction is a bit extreme: the contributing section is *barely* another fold down in this README than it is in the current one. I totally agree with the sentiment, but users of such technical sophistication are surely also aware of the `CONTRIBUTING.md` convention (and indeed we would be wise to have that file be in the root directory rather than a further step removed in docs, if this is such a burning concern). Also new contributors get `CONTRIBUTING.md` highlighted in a variety of places and banners, such as right at the top of issues. 

Screenshot 2021-01-25 at 11 11 13

**Comment by iamrecursion** [comment]
> Ugh I was afraid of this - will do another pass on it.

Looking forward to reading the update.

> Yeah I'm not sure...hopefully in the future something like [this](https://github.community/t/support-theme-context-for-images-in-light-vs-dark-mode/147981) lands and we can show different screens.

Well, fingers crossed.
 
> > Also, the "See it in action" link is butted right up against the screenshot and shouldn't be. Please make sure that there's a line break between it and the screenie.

Just to clarify, this should be left justified, and the image centre.

> GitHub really need to provide a way to hook into the currently used theme/user setting.

Yep.

> On it

Thanks

> Logo far too hefty - I might just move the shields out of that right adjusted area.

We definitely want it to look good on the app/mobile site too.

> Having said that, I think this reaction is a bit extreme: the contributing section is _barely_ another fold down in this README than it is in the current one. I totally agree with the sentiment, but users of such technical sophistication are surely also aware of the `CONTRIBUTING.md` convention (and indeed we would be wise to have that file be in the root directory rather than a further step removed in docs, if this is such a burning concern). Also new contributors get `CONTRIBUTING.md` highlighted in a variety of places and banners, such as right at the top of issues.

Good point with the highlights. We want it in the `docs/` folder so it's on `dev.enso.org`, whereas it wouldn't be in the root folder. Would you think it's a _problem_ to highlight it in the "Getting Started" section?

**Pull request merged**
