### PR TITLE
Fix AST.Block inconsistency between `reprBlock` and `ozipBlock`.

### PR DESCRIPTION
**Pull request by mwu-tow**
### Pull Request Description
This PR fixes the processing of empty lines in the `ozipBlock` method. Basically if the line does not contain AST, the block indent should not be added to it, and the line's offset represents total count of spaces in the line.

This inconsistency causes IDE issues, as the id map cannot properly roundtrip for modules containing empty lines in blocks.

### Important Notes
Not sure why every time scalafmt wants to reformat the file.

### Checklist
Please include the following checklist in your PR:

- [x] The documentation has been updated if necessary.
- [x] All code conforms to the [Scala](https://github.com/luna/enso/blob/master/docs/style-guide/scala.md) and [Java](https://github.com/luna/enso/blob/master/docs/style-guide/java.md) style guides.
- [x] All code has been tested where possible.

### CODE REVIEW

**Comment by mwu-tow** [comment]
@iamrecursion Github allows to hide whitespace changes in the "Files changed" view (the gear icon next to "Jump to…" picket).

> I think you may be using the wrong scalafmt version

How can I check this version or upgrade it?
I don't really remember setting this up manually, I thought it managed by sbt or Intellij.

**Comment by iamrecursion** [comment]
Thanks for the heads up! 

Editor -> Code Style -> Scala -> Formatter: Scalafmt. 

Version should be 2.4.2.

**Comment by mwu-tow** [comment]
Yep, this was a version problem. Intellij used config file from different working copy that wasn't updated for a while. 
I'll fix ws soon.

**Comment by iamrecursion** [comment]
Great, thanks!

**Comment by mwu-tow** [comment]
whitespace should be fine now, there's one minor change left but it looks reasonable

**Comment by mwu-tow** [comment]
Oh, I thought we use the "single item - single line" approach.
Pushed the optimized version.

**Pull request merged**
